#!/usr/bin/env bash
#Configuire Nginx server to listen port 80

# Remove default nginx configuration
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart 
